service: example-lambda-xray-py
provider:
  name: aws
  runtime: python2.7
  iamRoleStatements:
      -  Effect: "Allow"
         Action:
           - "xray:PutTraceSegments"
           - "xray:PutTelemetryRecords"
           - "iam:Get*"
         Resource:
           - "*"
package:
  include:
    - .vendor/**

functions:
  hello:
    handler: handler.hello